linters:
  ColorVariable:
    enabled: false
  HexNotation:
    style: lowercase
  MergeableSelector:
    force_nesting: false
  Indentation:
    allow_non_nested_indentation: true
    width: 4
  PropertySortOrder:
    order: recess
  SelectorFormat:
    convention: hyphenated_BEM
